osx_image: xcode11.3
language: swift
before_install:
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/CalendarSwift.xcworkspace -scheme CalendarSwift-Example -destination 'platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro' | xcpretty
